name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pandas=1.2.3
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=20.3.3
  - pip:
      - wandb==0.10.31